name: flowblade-azure-sql-edge

services:
  azure-sql-edge:
    container_name: sql-server-db
    image: mcr.microsoft.com/azure-sql-edge
    cap_add: ['SYS_PTRACE']
    ports:
      - '1433:1433'
    env_file:
      - .env.azure-sql-edge.development
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q "SELECT 1" -b -o /dev/null
      interval: 1s
      timeout: 30s
      retries: 30
      start_period: 5s
    networks:
      - flowblade-dev-network
    volumes:
      - flowblade-azure-sql-edge:/var/opt/mssql:rw

volumes:
  flowblade-azure-sql-edge:

networks:
  flowblade-dev-network:
    driver: bridge
    enable_ipv6: false
