name: flowblade-postgres

services:
  postgres:
    container_name: flowblade-postgres
    image: postgres:17.3-alpine3.21
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    networks:
      - flowblade-net
    env_file:
      - .env.postgres.development
    volumes:
      - postgres_db_data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead,
      # so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
  postgres_db_data:

networks:
  flowblade-net:
    driver: bridge
    enable_ipv6: false
